- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
> Installing Devise

- app/models/review.rb
- db/migrate/20210817183406_create_reviews.rb
- db/schema.rb
- test/models/review_test.rb
remember to run db:migrate, yarn and bundle.
> I created Review model

- app/models/category.rb
- db/migrate/20210817183435_create_categories.rb
- db/schema.rb
- test/models/category_test.rb
> creating category model

- app/models/category.rb
- app/models/master.rb
- app/models/user.rb
- db/migrate/20210817193956_create_masters.rb
- db/schema.rb
- test/models/master_test.rb
remember to run bundle, yarn and db:migrate.
> Master model created

- app/models/master.rb
- app/models/order.rb
- app/models/review.rb
- app/models/user.rb
- db/migrate/20210817201606_create_orders.rb
- db/schema.rb
- test/models/order_test.rb
> crating order model

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20210817204336_create_active_storage_tables.active_storage.rb
- db/schema.rb
Don't forget run bundle install, yarn install and rails db:migrate
> Adding cloudinary

- app/controllers/categories_controller.rb
- test/controllers/categories_controller_test.rb
Please, confirm creating category controller
> Creating controller category

- app/controllers/masters_controller.rb
- test/controllers/masters_controller_test.rb
Remember run yarn, bundle and db:migrate.
> Masters controller created

- app/controllers/orders_controller.rb
- app/controllers/reviews_controller.rb
- test/controllers/orders_controller_test.rb
- test/controllers/reviews_controller_test.rb
Orders and Reviews Controllers
> Added reviews and orders controllers

- db/migrate/20210818213501_remove_review_to_orders.rb
- db/migrate/20210818214040_add_references_to_reviews.rb
- db/schema.rb
> Changing references in order and review models

- app/controllers/users_controller.rb
- config/routes.rb
- test/controllers/users_controller_test.rb
> Added routes and users#show action

- app/models/master.rb
- app/models/order.rb
- app/models/review.rb
- app/models/user.rb
- config/routes.rb
New routes and models corrections
> Add routes and relations in models

- app/controllers/masters_controller.rb
- app/models/master.rb
- app/views/masters/edit.html.erb
- app/views/masters/index.html.erb
- app/views/masters/new.html.erb
- app/views/masters/show.html.erb
- app/views/users/show.html.erb
- config/routes.rb
remember run yarn, bundle and db:migrate.
> view of user and master created, and other changes

- app/controllers/masters_controller.rb
- app/views/masters/edit.html.erb
- app/views/masters/new.html.erb
Ya equipazo, reparé el problema de los nuevos maestros. Ahora estaríamos listos para seguir
> Repairing new and edit action and view of master

- app/assets/stylesheets/components/_card.scss
- app/models/user.rb
- app/views/masters/index.html.erb
Me queda pendiente la imagen, no la he podido dejar en el bottom
> row and col in the views Masters

- app/assets/stylesheets/components/_carrusel.scss
- app/assets/stylesheets/components/_index.scss
- app/views/masters/new.html.erb
- app/views/masters/show.html.erb
- app/views/users/show.html.erb
remember run bulde, yarn and db:migrate
> carrusel created

- app/assets/stylesheets/components/_carrusel.scss
- app/views/masters/show.html.erb
> best frontend

- app/assets/stylesheets/components/_carrusel.scss
- app/views/masters/show.html.erb
i mejorated carrousel and components.
> best frontend in master-show

- app/assets/stylesheets/components/_carrusel.scss
- app/controllers/users_controller.rb
- app/views/masters/show.html.erb
- app/views/users/show.html.erb
frontend in show of user and master
> better frontend in master and user show

- Gemfile
- Gemfile.lock
- app/controllers/categories_controller.rb
- app/controllers/masters_controller.rb
- app/controllers/users_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/javascript/plugins/init_mapbox.js
- app/models/master.rb
- app/models/order.rb
- app/models/user.rb
- app/views/categories/index.html.erb
- app/views/categories/show.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/layouts/application.html.erb
- app/views/masters/index.html.erb
- app/views/masters/show.html.erb
- app/views/shared/_masters-results.html.erb
- app/views/users/show.html.erb
- config/initializers/geocoder.rb
- config/routes.rb
- db/migrate/20210824181850_add_coordinates_to_users.rb
- db/migrate/20210824181901_add_coordinates_to_masters.rb
- db/schema.rb
- package.json
- yarn.lock
You must do bundle install, yarn install and rails db:migrate
> Adding Geocoding and several other changes

- app/views/users/show.html.erb
se agregaron link en las card y se mejoro el codigo de la alerta
> mejoras en vista y se agregaron link  las cards

- app/assets/stylesheets/components/_carrusel.scss
- app/assets/stylesheets/components/_wrapper.scss
- app/views/shared/_masters-results.html.erb
> Add change code

- app/assets/stylesheets/pages/_home.scss
- app/controllers/orders_controller.rb
- app/controllers/reviews_controller.rb
- app/views/layouts/application.html.erb
- app/views/orders/show.html.erb
- config/routes.rb
Cada día falta menos para terminar! Vamos, que se puede!
> Improving show of orders and new and show of reviews

- app/controllers/categories_controller.rb
- app/controllers/pages_controller.rb
- app/javascript/components/bar_rating.js
- app/javascript/packs/application.js
- app/views/categories/new.html.erb
- app/views/layouts/application.html.erb
- app/views/masters/show.html.erb
- app/views/orders/show.html.erb
- app/views/pages/help.html.erb
- app/views/pages/we.html.erb
- app/views/shared/_masters-results.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20210831220226_add_admin_to_users.rb
- db/schema.rb
- package.json
- yarn.lock
Hice varias mejoras; les envié fotos de cómo quedaron.
Esta vez es estrictamente necesario que corran:
bundle install && yarn install && rails db:migrate
Si lo olvidan, tendrán errores.
> Several changes

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/masters_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- app/policies/application_policy.rb
- app/policies/category_policy.rb
- app/policies/master_policy.rb
- app/policies/order_policy.rb
- app/policies/review_policy.rb
- app/policies/user_policy.rb
- app/views/categories/new.html.erb
- app/views/categories/show.html.erb
- app/views/masters/index.html.erb
- app/views/masters/new.html.erb
- app/views/orders/new.html.erb
- app/views/shared/_masters-results.html.erb
- test/policies/category_policy_test.rb
- test/policies/master_policy_test.rb
- test/policies/order_policy_test.rb
- test/policies/review_policy_test.rb
- test/policies/user_policy_test.rb
Avances de hoy, mañana seguimos: a la misma hora, en el mismo canal.
> Adding punding authorization
